### ISSUE TITLE
Bug: Shallow copy causes only loop once !

### ISSUE THREAD

**Issue by wuyuanmm** [jlparkI/outlier_robust_polyfit#2]
I test the RobustPolyfit.pyx ,tranlate this code to prue python in python 3.7, and I find  Shallow copy causes only loop once. 

      for i in range(self.max_iter):
          resp, current_bound[0] = self.e_step(y, preds)
          preds = self.m_step(X_, y, resp)
          change[0] = current_bound[0] - lower_bound[0]
          weight_change = np.max(np.abs(old_weights / self.weights) - 1 )
          if np.abs(change[0]) < self.tol or weight_change < 1e-3:
              self.converged = True
              self.weights = self.weights / norms
              break
          lower_bound = current_bound   #should be  : current_bound.copy()
          old_weights = self.weights

**Comment by jlparkI** [comment]
I did not encounter this issue previously after compiling the code using Cython -- maybe it only occurs when translating the code to Python. However, either way it is easy to fix. I've updated this and will push a new version of the package shortly.

This also reminds me there are some additional modules I've been meaning to add to this, will do that soon.

Thanks

**Comment by wuyuanmm** [comment]
Thank you for your reply. I found it while debugging the python code. In addition, I have transferred the code to C++, including opencv and Eigen libraries (to achieve QR decomposition, you can also use opencv to achieve), but I haven’t done further optimization yet. If you wish, I will provide an optimized version of C++ as soon as possible.  I will close the issue !

**Comment by jlparkI** [comment]
There are actually a number of changes I would like to make to this package -- there is a better approach we can use to finding starting parameters -- fairly important since the optimization problem is often non-convex for this algorithm, especially once we extend this to multivariate linear / polynomial fitting (which is also another feature I'd like to add to this). So I'm anticipating uploading a new version of this with a lot of improvements sometime soon -- I just haven't found time to complete it yet. For now I'll close this issue and upload a new version with this minor bug fix tomorrow. Thanks.
